import './components/header.js'
import './components/transfer.js'
import './components/swipers.js'
import './components/form.js'
import './components/accordion.js'
import './components/offcanvas.js'
import './components/dropdown.js'
